auction/urls.py
from django.urls import path
from .views import AuctionDetailView, AuctionView

app_name = "auction"

urlpatterns = [
    path("", AuctionView.as_view(), name="auctions"),
    path("<int:auction_id>/", AuctionDetailView.as_view(), name="auction_detail"),
]

cozy_clothings/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("", include("user_management.urls")),
    path("products/", include("product.urls")),
    path("auction/", include("auction.urls")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path

from product.views import (
    ProductView,
    DetailProductView,
    CartView,
    UserCartView,
    CheckoutView,
    CreateOrderView,
    OrderView,
    DetailOrderView,
    PaymentView,
    PurchaseView,
)

app_name = "product"

urlpatterns = [
    path("", ProductView.as_view(), name="products"),
    path("<int:product_id>/", DetailProductView.as_view(), name="detail_product"),
    path(
        "add-remove-from-cart/<int:product_id>/",
        CartView.as_view(),
        name="add_remove_from_cart",
    ),
    path(
        "user-cart/",
        UserCartView.as_view(),
        name="user_cart",
    ),
    path(
        "checkout/",
        CheckoutView.as_view(),
        name="checkout",
    ),
    path("create-order/", CreateOrderView.as_view(), name="create_order"),
    path("orders/", OrderView.as_view(), name="orders"),
    path("order/<int:order_id>/", DetailOrderView.as_view(), name="order_detail"),
    path(
        "payment/<int:order_id>/",
        PaymentView.as_view(),
        name="payment",
    ),
    path("purchase/", PurchaseView.as_view(), name="purchase"),
]

product/forms.py
from django import forms


class PaymentForm(forms.Form):
    order_id = forms.IntegerField(widget=forms.HiddenInput())
    shipping_address = forms.CharField(
        widget=forms.TextInput(attrs={"class": "w-full py-4 px-6 rounded-xl border"}),
        label="Shipping Address",
    )
    payment_method = forms.ChoiceField(
        choices=[
            ("esewa", "Esewa"),
            ("khalti", "Khalti"),
        ],
        widget=forms.RadioSelect(attrs={"class": "w-full py-4 px-6 rounded-xl border"}),
        label="Payment Method",
    )

product/views.py
import requests
import json
import uuid
import hmac
import hashlib
import base64

from django.shortcuts import render, redirect
from django.views import View
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.conf import settings
from django.utils import timezone

from product.models import Product, Category, Cart, Order, OrderItem, PaymentHistory
from product.forms import PaymentForm
from product.tasks import (
    send_order_placement_email_task,
    send_payment_confirmation_email_task,
)


class ProductView(View):
    template_name = "product/products.html"

    def get(self, request):
        products = Product.objects.filter(is_active=True, is_auction_product=False)
        categories = Category.objects.all()

        query = request.GET.get("query", "")
        category_id = request.GET.get("category", 0)

        if category_id:
            products = products.filter(category_id=category_id)

        if query:
            products = products.filter(
                Q(title__icontains=query)
                | Q(description__icontains=query)
                | Q(category__title__icontains=query)
            ).filter(is_active=True, is_auction_product=False)

        return render(
            request,
            self.template_name,
            {
                "products": products,
                "categories": categories,
                "query": query,
                "category_id": int(category_id),
            },
        )


class DetailProductView(View):
    template_name = "product/detail_product.html"

    def get(self, request, *args, **kwargs):
        product_id = kwargs.get("product_id")
        product = get_object_or_404(Product, id=product_id)
        related_products = Product.objects.filter(category=product.category).exclude(
            id=product_id
        )[:3]

        return render(
            request,
            self.template_name,
            {
                "product": product,
                "related_products": related_products,
            },
        )


class CartView(View):
    def post(self, request, *args, **kwargs):
        product_id = kwargs.get("product_id")
        quantity = int(request.POST.get("quantity", 1))

        product = get_object_or_404(Product, id=product_id)

        # Check if the quantity requested is valid
        if quantity > product.quantity:
            return JsonResponse(
                {
                    "success": False,
                    "error": f"Only {product.quantity} more units available.",
                },
                status=400,
            )

        cart_item, created = Cart.objects.get_or_create(
            user=request.user, product=product
        )

        cart_item.quantity = quantity
        cart_item.save()

        return JsonResponse(
            {
                "message": "Product added to cart successfully",
                "product_title": product.title,
                "quantity": cart_item.quantity,
                "total_price": cart_item.total_price(),
            }
        )

    def delete(self, request, *args, **kwargs):
        product_id = kwargs.get("product_id")
        product = get_object_or_404(Product, id=product_id)

        # Try to find the cart item for this product
        cart_item = Cart.objects.filter(user=request.user, product=product).first()

        if cart_item:
            cart_item.delete()
            return JsonResponse(
                {"success": True, "message": "Product removed from cart successfully."},
                status=200,
            )

        return JsonResponse(
            {"error": "Product not found in cart."},
            status=400,
        )


class UserCartView(View):
    template_name = "product/cart.html"

    def get(self, request, *args, **kwargs):
        cart_items = Cart.objects.filter(user=request.user)

        # Calculate the total price of the items in the cart
        total_price = sum(item.total_price() for item in cart_items)

        return render(
            request,
            self.template_name,
            {"cart_items": cart_items, "total_price": total_price},
        )


class CheckoutView(View):
    template_name = "product/checkout.html"

    def get_cart_items(self, user):
        # Fetch the user's cart items (adjust this to your actual data retrieval logic)
        user_cart_items = Cart.objects.filter(user=user)
        return [
            {
                "product": item.product.title,
                "is_auction_product": item.product.is_auction_product,
                "quantity": item.quantity,
                "price": item.product.sale_price,
                "total_price": item.total_price(),
            }
            for item in user_cart_items
        ]

    def get(self, request, *args, **kwargs):
        user_cart_items = self.get_cart_items(request.user)
        total_price = sum(item.get("total_price") for item in user_cart_items)

        return render(
            request,
            self.template_name,
            {
                "cart_items": user_cart_items,
                "total_price": total_price,
            },
        )


class CreateOrderView(View):
    template_name = "product/orders.html"

    def get(self, request, *args, **kwargs):
        cart_items = Cart.objects.filter(user=request.user)

        total_price = sum(item.total_price() for item in cart_items)

        order = Order.objects.create(
            user=request.user,
            total_price=total_price,
            status="Pending",
        )

        for cart_item in cart_items:
            OrderItem.objects.create(
                order=order,
                product=cart_item.product,
                quantity=cart_item.quantity,
                price=cart_item.product.sale_price,
            )

        cart_items.delete()  # Clear the cart after creating the order
        send_order_placement_email_task.delay(
            user_email=request.user.email,
            username=request.user.username,
            order_id=order.id,
            total_amount=order.total_price,
        )

        return redirect("product:order_detail", order_id=order.id)


class OrderView(View):
    template_name = "product/orders.html"

    def get(self, request, *args, **kwargs):
        orders = Order.objects.filter(user=request.user)

        return render(request, self.template_name, {"orders": orders})


class DetailOrderView(View):
    template_name = "product/detail_order.html"

    def get(self, request, *args, **kwargs):
        order_id = kwargs.get("order_id")
        order = get_object_or_404(Order, id=order_id, user=request.user)
        order_items = order.items.all()

        # Fetch the latest ended auction for auctioned products
        for item in order_items:
            if item.product.is_auction_product:
                auction = (
                    item.product.auction.filter(end_time__lte=timezone.now())
                    .order_by("-end_time")
                    .first()
                )
                item.auction_price = (
                    auction.current_price if auction else 0
                )  # Attach dynamic price

        return render(
            request, self.template_name, {"order": order, "order_items": order_items}
        )


class PaymentView(View):
    template_name = "product/payment.html"
    form_class = PaymentForm

    def get(self, request, *args, **kwargs):
        order_id = kwargs.get("order_id")

        order = get_object_or_404(Order, id=order_id, user=request.user)
        total_price = order.total_price

        form = self.form_class()

        return render(
            request,
            self.template_name,
            {
                "order": order,
                "total_price": total_price,
                "form": form,
            },
        )

    def post(self, request, *args, **kwargs):
        user = request.user
        order_id = kwargs.get("order_id")
        form = self.form_class(request.POST)

        order = get_object_or_404(Order, id=order_id, user=request.user)

        if form.is_valid():
            address = form.cleaned_data.get("shipping_address")
            payment_method = form.cleaned_data.get("payment_method").lower()

            total_price, product_details = self._process_order_details(
                order, user, payment_method, address
            )
            if payment_method == "esewa":
                return self._handle_esewa_payment(request, order, total_price)
            elif payment_method == "khalti":
                payment_url = self._handle_khalti_payment(
                    order, total_price, product_details
                )
                return redirect(payment_url)
        else:
            return render(
                request,
                self.template_name,
                {
                    "order": order,
                    "total_price": order.total_price,
                    "form": form,
                },
            )

    # custom methods to handle payments
    def _process_order_details(self, order, user, payment, shipping_address):
        total_amount = 0
        product_details = []

        order.shipping_address = shipping_address
        order.save()

        order_items = OrderItem.objects.filter(order=order)

        for order_item in order_items:
            product = order_item.product
            quantity = order_item.quantity

            if quantity > product.quantity:
                raise ValueError(f"Insufficient stock for {product.title}")

            # Determine the correct price
            if product.is_auction_product:
                # Fetch the latest auction price
                auction = (
                    product.auction.filter(end_time__lte=timezone.now())
                    .order_by("-end_time")
                    .first()
                )

product/templates/product/cart.html
{% extends 'user_management/base.html' %}
{% block title %}Shopping Cart{% endblock %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'product/css/style.css' %}">
{% endblock %}

{% block content %}
<div id="message-container" class="hidden mb-4"></div>
<div class="max-w-7xl mx-auto px-4 py-8">
    <h1 class="text-2xl font-semibold mb-6">Your Shopping Cart</h1>

    {% if cart_items %}
    <div class="overflow-x-auto bg-white shadow rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-100">
                <tr>
                    <th scope="col"
                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Product
                    </th>
                    <th scope="col"
                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Quantity
                    </th>
                    <th scope="col"
                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Price
                    </th>
                    <th scope="col"
                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Total
                    </th>
                    <th scope="col" class="relative px-6 py-3">
                        <span class="sr-only">Remove</span>
                    </th>
                </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
                {% for item in cart_items %}
                <tr id="cart-item-{{ item.product.id }}">
                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 flex">
                        <img src="{{ item.product.image.url }}" alt="{{ item.product.title }}"
                            class="w-8 h-8 object-cover rounded-sm mr-6">
                        {{ item.product.title }}
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        <div class="flex items-center space-x-2">
                            {% if not item.product.is_auction_product %}
                            <!-- Decrease Quantity Button -->
                            <button type="button" id="quantity-minus"
                                class="bg-red-500 text-white px-2 py-1 rounded hover:bg-red-600 text-xs"
                                data-type="minus" data-id="{{ item.id }}" title="Decrease quantity">
                                <i class="fas fa-minus"></i>
                            </button>

                            <!-- Quantity Input -->
                            <input type="number" id="quantity_{{ item.id }}"
                                class="quantity-input w-16 border border-gray-300 rounded-md py-1 text-center"
                                data-product-id="{{ item.product.id }}" data-price="{{ item.product.sale_price }}"
                                data-id="{{ item.id }}" value="{{ item.quantity }}" min="1"
                                max="{{ item.product.quantity }}" />

                            <!-- Increase Quantity Button -->
                            <button type="button" id="quantity-plus"
                                class="bg-green-500 text-white px-2 py-1 rounded hover:bg-green-600 text-xs"
                                data-type="plus" data-id="{{ item.id }}" title="Increase quantity">
                                <i class="fas fa-plus"></i>
                            </button>
                            {% else %}
                            <span class="text-black-500">{{ item.quantity }}</span>
                            {% endif %}
                        </div>
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        {% if not item.product.is_auction_product %}
                        Rs. {{ item.product.sale_price }}
                        {% endif %}
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        Rs. <span id="total-price-{{ item.id }}">{{ item.total_price }}</span>
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                        {% if not item.product.is_auction_product %}
                        <button class="text-red-600 hover:text-red-800 remove-item-btn"
                            data-product-id="{{ item.product.id }}" title="Remove item">
                            <i class="fas fa-trash-alt"></i> Remove
                        </button>
                        {% else %}
                        <span class="text-black-500">Auctioned Product</span>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="mt-8 flex justify-between items-center">
        <div class="text-xl font-semibold">
            Total: Rs. <span id="grand-total-price">{{ total_price }}</span>
        </div>
        <div>
            <a id="checkout-btn" href="{% url 'product:checkout' %}"
                class="bg-blue-500 text-white px-6 py-2 rounded hover:bg-blue-600 flex items-center space-x-2">
                <i class="fas fa-credit-card"></i>
                <span>Proceed to Checkout</span>
            </a>
        </div>
    </div>
    {% else %}
    <p class="text-center text-lg font-medium text-gray-600">
        Oops! Your cart is empty. <br />
        <a href="{% url 'product:products' %}" class="text-2xl text-pink-500">Click Here to Browse!</a>
    </p>
    {% endif %}
</div>
{% include 'product/snippets/checkout_functionalities.html' %}
{% endblock %}

product/templates/product/checkout.html
{% extends 'user_management/base.html' %}
{% block title %}Checkout{% endblock %}
{% load static %}
{% block extra_css %}
{% endblock %}

{% block content %}
<div class="max-w-7xl mx-auto px-4 py-8">
    <h1 class="text-2xl font-semibold mb-6">Checkout</h1>

    {% if cart_items %}
    <div class="overflow-x-auto bg-white shadow rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-100">
                <tr>
                    <th scope="col"
                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Product
                    </th>
                    <th scope="col"
                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Quantity
                    </th>
                    <th scope="col"
                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Price
                    </th>
                    <th scope="col"
                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Total
                    </th>
                </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
                {% for item in cart_items %}
                <tr>
                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                        <i class="fas fa-cube mr-2 text-gray-400"></i>{{ item.product }}
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{{ item.quantity }}</td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        {% if not item.is_auction_product %}
                        Rs. {{ item.price }}
                        {% endif %}
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">Rs. {{ item.total_price }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="mt-8 flex justify-between items-center">
        <div class="text-xl font-semibold">
            Total: Rs. {{ total_price }}
        </div>
        <div class="ml-auto">
            <a href="{% url 'product:create_order' %}"
                class="bg-teal-500 text-white px-6 py-2 rounded hover:bg-teal-600 flex items-center space-x-2">
                <i class="fas fa-check-circle"></i>
                <span>Create Order</span>
            </a>
        </div>
    </div>

    <div class="mt-8">
        <a href="{% url 'product:user_cart' %}"
            class="bg-red-500 text-white px-6 py-2 rounded hover:bg-red-600 space-x-2">
            <i class="fas fa-arrow-left"></i>
            <span>Back to Cart</span>
        </a>
    </div>

    {% else %}
    <p class="text-center text-lg font-medium text-gray-600">
        Oops! Your cart is empty. <br />
        <a href="{% url 'product:products' %}" class="text-2xl text-pink-500">Click Here to Browse!</a>
    </p>
    {% endif %}
</div>
{% endblock %}

product/templates/product/esewa_checkout.html
{% extends 'user_management/base.html' %} {% load static %}
{% block title %} Checkout {%endblock %}
{% block content %}
<section id="billboard" class="bg-light py-5">
    <div class="container">
        <div class="row justify-content-center">
            <h1 class="section-title text-center mt-4" data-aos="fade-up">
                {{category.title}}
            </h1>
        </div>
        <div class="container">
            <form action="https://rc-epay.esewa.com.np/api/epay/main/v2/form" method="POST" name="esewa-form">
                {% for field, value in esewa_fields.items %}
                <input type="hidden" name="{{ field }}" value="{{ value }}" />
                {% endfor %}
                <button type="submit" class="btn btn-primary">Pay with eSewa</button>
            </form>
            <script>
                window.onload = function () {
                    document.forms['esewa-form'].submit();
                }
            </script>
        </div>
    </div>
</section>

{% endblock %}

product/templates/product/orders.html
{% extends 'user_management/base.html' %}
{% block title %}Your Orders{% endblock %}
{% load static %}
{% block extra_css %}
{% endblock %}

{% block content %}
<div class="max-w-7xl mx-auto px-4 py-8">
    <h1 class="text-2xl font-semibold mb-6">
        <i class="fas fa-box-open mr-2 text-gray-400"></i> Your Orders
    </h1>

    {% if orders %}
    <div class="overflow-x-auto bg-white shadow-lg rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-100">
                <tr>
                    <th scope="col"
                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Order ID
                    </th>
                    <th scope="col"
                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Status
                    </th>
                    <th scope="col"
                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Total Price
                    </th>
                    <th scope="col"
                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Created At
                    </th>
                    <th scope="col"
                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Action
                    </th>
                </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
                {% for order in orders %}
                <tr>
                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                        <i class="fas fa-hashtag mr-2 text-gray-400"></i>{{ order.id }}
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        {% if order.status == 'Pending' %}
                        <span class="text-yellow-500 font-semibold">
                            <i class="fas fa-clock mr-2"></i>{{ order.status }}
                        </span>
                        {% elif order.status == 'Paid' %}
                        <span class="text-green-500 font-semibold">
                            <i class="fas fa-credit-card mr-2"></i>{{ order.status }}
                        </span>
                        {% else %}
                        <span class="text-blue-500 font-semibold">
                            <i class="fas fa-check-circle mr-2"></i>{{ order.status }}
                        </span>
                        {% endif %}
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        <i class="fas fa-rupee-sign mr-2 text-gray-400"></i>Rs. {{ order.total_price }}
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        <i class="fas fa-calendar-alt mr-2 text-gray-400"></i>{{ order.created_at }}
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                        <a href="{% url 'product:order_detail' order.id %}"
                            class="text-indigo-600 hover:text-indigo-900 flex items-center space-x-2">
                            <i class="fas fa-eye"></i>
                            <span>View Details</span>
                        </a>
                        {% if order.status == 'Pending' %}
                        <a href="{% url 'product:payment' order.id %}"
                            class="mt-4 ml-4 text-teal-600 hover:text-teal-800 flex items-center space-x-2">
                            <i class="fas fa-credit-card"></i>
                            <span>Pay Now</span>
                        </a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    {% else %}
    <p class="text-center text-lg font-medium text-gray-600">
        <i class="fas fa-exclamation-circle mr-2 text-gray-400"></i>
        You have no orders yet. <br />
        <a href="{% url 'product:products' %}" class="text-2xl text-pink-500">
            Browse Products to Make an Order!
        </a>
    </p>
    {% endif %}
</div>
{% endblock %}

product/templates/product/products.html
{% extends 'user_management/base.html' %}
{% block title %}Products{% endblock %}
{% block content %}
<div class="grid grid-cols-1 md:grid-cols-4 gap-6">
    <!-- Sidebar -->
    <div class="col-span-1 bg-gray-100 rounded-xl p-6 shadow-md">
        <form method="get" action="{% url 'product:products' %}">
            <div class="relative">
                <input name="query"
                    class="w-full py-4 px-6 border rounded-xl focus:outline-none focus:ring-2 focus:ring-teal-500"
                    type="text" value="{{ query }}" placeholder="Search">
                <button class="absolute right-2 top-2 py-2 px-4 bg-teal-500 text-white rounded-xl hover:bg-teal-400">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                        <path fill-rule="evenodd"
                            d="M8 4a6 6 0 100 12 6 6 0 000-12zM2 8a8 8 0 1115.51 3.47l4.15 4.15a1 1 0 01-1.42 1.42l-4.15-4.15A8 8 0 012 8z"
                            clip-rule="evenodd" />
                    </svg>
                </button>
            </div>
        </form>

        <hr class="my-6 border-gray-300">
        <p class="font-semibold text-gray-700">Categories</p>
        <ul class="mt-4 space-y-2">
            {% for category in categories %}
            <a href="{% url 'product:products' %}?query={{ query }}&category={{ category.id }}"
                class="text-gray-700 hover:text-blue-500">
                <li
                    class="py-2 px-4 rounded-xl hover:bg-blue-100 {% if category.id == category_id %} bg-blue-300 {% endif %}">
                    {{ category.title }}
                </li>
            </a>
            {% endfor %}
        </ul>

        <hr class="my-6 border-gray-300">
        <a href="{% url 'product:products' %}"
            class="block py-3 px-6 text-lg text-center bg-yellow-500 text-white rounded-xl hover:bg-yellow-400">Clear
            Filters</a>
    </div>

    <!-- Products List -->
    <div class="col-span-3 bg-white p-6 rounded-xl shadow-md">
        <h2 class="mb-8 text-3xl text-center font-semibold text-gray-800">Products</h2>
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {% for product in products %}
            <div
                class="bg-gray-50 rounded-xl overflow-hidden shadow hover:shadow-lg transition duration-300 hover:scale-105">
                <a href="{% url 'product:detail_product' product.id %}" class="block">
                    <div class="relative h-64">
                        <img src="{{ product.image.url }}" alt="{{ product.title }}" class="object-cover w-full h-full">
                        {% if product.discount_percentage > 0 %}
                        <div class="absolute top-2 right-2 bg-teal-500 text-white py-1 px-3 text-sm rounded-lg">
                            -{{ product.discount_percentage }}%
                        </div>
                        {% endif %}
                    </div>
                    <div class="p-4">
                        <h3 class="text-xl font-bold text-gray-800 truncate">{{ product.title }}</h3>
                        <div class="mt-2 flex items-center justify-between">
                            <p class="text-lg text-teal-500 font-semibold">Rs. {{ product.sale_price }}</p>
                            {% if product.discount_percentage > 0 %}
                            <p class="text-sm text-gray-500 line-through">Rs. {{ product.price }}</p>
                            {% endif %}
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}